#!/bin/sh
# MAKE SURE TO CHMOD 0755 THESE SO SERVER CAN EXECUTE THEM
# build script to run branch release
# ian drosos

echo "Received message to build branch release"

# checkout branch
# http://stackoverflow.com/questions/1386291/git-git-dir-not-working-as-expected
git -C "/home/ubuntu/Complexity" checkout "release"
git -C "/home/ubuntu/Complexity" pull
# clean build
rm -rf "/home/ubuntu/Complexity/node_modules"
# build
npm --prefix /home/ubuntu/Complexity install /home/ubuntu/Complexity
