#!/bin/sh
# MAKE SURE TO CHMOD 0755 THESE SO SERVER CAN EXECUTE THEM
# build script to run branch dev
# ian drosos

echo "Running build script.\n"

# checkout branch
# http://stackoverflow.com/questions/1386291/git-git-dir-not-working-as-expected
git -C "/home/ubuntu/Complexity" checkout "dev"
git -C "/home/ubuntu/Complexity" pull
echo "Pulled latest code.\n"

# clean build
rm -rf "/home/ubuntu/Complexity/node_modules"
rm -rf "/home/ubuntu/Complexity/etc"
echo "Cleaned working directory."

# build
echo "Starting build."
npm --prefix /home/ubuntu/Complexity install /home/ubuntu/Complexity
