#!/bin/sh
# MAKE SURE TO CHMOD 0755 THESE SO SERVER CAN EXECUTE THEM
# build script to run branch dev
# ian drosos

echo "Running build script.\n"

# checkout branch
# http://stackoverflow.com/questions/1386291/git-git-dir-not-working-as-expected
# git -C "/home/ubuntu/Complexity" checkout "dev"
# git -C "/home/ubuntu/Complexity" pull
git -C "/home/ubuntu/react-markdown" checkout "dev"
git -C "/home/ubuntu/react-markdown" pull
echo "Pulled latest code.\n"

# clean build
rm -rf "/home/ubuntu/react-markdown/node_modules"
rm -rf "/home/ubuntu/react-markdown/etc"
echo "Cleaned working directory."

# build
echo "Starting build."
npm cache -f clean && npm --prefix /home/ubuntu/react-markdown install --save /home/ubuntu/react-markdown
npm --prefix /home/ubuntu/react-markdown install --save json-loader
