#!/bin/sh

echo "Running mail script."

IFS=''

while read line
do
echo "Sending mail to " $line
if ($3 eq "true") then
	subject='react-markdown status: successful for '$2' build'
else
	subject='react-markdown status: failed for '$2' build'
fi
cat $1 | mail -s $subject $line  
done < ./scripts/email_ids